export const GET_COURSES = "GET_COURSES";
export const GET_COURSE_DETAIL = "GET_COURSE_DETAIL";
export const COURSE_ERROR = "COURSE_ERROR";
export const SET_LOADING = "SET_LOADING";
export const ADD_ENROLL_COURSE = "ADD_ENROLL_COURSE";
export const ENROLL_COURSE_ERROR = "ENROLL_COURSE_ERROR";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const LOCATION_ERROR = "LOCATION_ERROR";
